GET http://ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/ContactSet

###
GET https://port4004-workspaces-ws-5sc2k.us10.trial.applicationstudio.cloud.sap/odata/v4/contactbookservice/Team
Cookie: dtCookie=v_4_srv_6_sn_68FF3A7DCAD76B75E21E1670ED0DF1FD_perc_100000_ol_0_mul_1_app-3Acab67a9e1543df82_0; workspaces-ws-5sc2k_WSR_SESSIONID=89oy+auNYoFjwqR1HwL1R1xeNuq/3rKZVx/rLddhs9SwHJYBYd6ZJJ/bRawYCsqOqPf8RthUDwWwkkAc3pjPnA==; country=AU; s_plt=4.52; s_pltp=undefined; AMCVS_227AC2D754DCAB340A4C98C6%40AdobeOrg=1; AMCV_227AC2D754DCAB340A4C98C6%40AdobeOrg=179643557%7CMCIDTS%7C19908%7CMCMID%7C85648936478962609373915698251042768522%7CMCAAMLH-1720595787%7C8%7CMCAAMB-1720595787%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1719998187s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.5.0; s_cc=true

###
GET https://port4004-workspaces-ws-5sc2k.us10.trial.applicationstudio.cloud.sap/odata/v4/contactbookservice/Contacts
Cookie: dtCookie=v_4_srv_6_sn_68FF3A7DCAD76B75E21E1670ED0DF1FD_perc_100000_ol_0_mul_1_app-3Acab67a9e1543df82_0; workspaces-ws-5sc2k_WSR_SESSIONID=89oy+auNYoFjwqR1HwL1R1xeNuq/3rKZVx/rLddhs9SwHJYBYd6ZJJ/bRawYCsqOqPf8RthUDwWwkkAc3pjPnA==; country=AU; s_plt=4.52; s_pltp=undefined; AMCVS_227AC2D754DCAB340A4C98C6%40AdobeOrg=1; AMCV_227AC2D754DCAB340A4C98C6%40AdobeOrg=179643557%7CMCIDTS%7C19908%7CMCMID%7C85648936478962609373915698251042768522%7CMCAAMLH-1720595787%7C8%7CMCAAMB-1720595787%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1719998187s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.5.0; s_cc=true
Content-Type: application/json
X-CSRF-Token: fetch

###


POST https://port41809-workspaces-ws-5sc2k.us10.trial.applicationstudio.cloud.sap/odata/v4/contactbookservice/Contacts
Cookie: dtCookie=v_4_srv_6_sn_68FF3A7DCAD76B75E21E1670ED0DF1FD_perc_100000_ol_0_mul_1_app-3Acab67a9e1543df82_0; workspaces-ws-5sc2k_WSR_SESSIONID=89oy+auNYoFjwqR1HwL1R1xeNuq/3rKZVx/rLddhs9SwHJYBYd6ZJJ/bRawYCsqOqPf8RthUDwWwkkAc3pjPnA==; country=AU; s_plt=4.52; s_pltp=undefined; AMCVS_227AC2D754DCAB340A4C98C6%40AdobeOrg=1; AMCV_227AC2D754DCAB340A4C98C6%40AdobeOrg=179643557%7CMCIDTS%7C19908%7CMCMID%7C85648936478962609373915698251042768522%7CMCAAMLH-1720595787%7C8%7CMCAAMB-1720595787%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1719998187s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.5.0; s_cc=true
Content-Type: application/json

{
    "ID" : "100000",
    "FirstName" : "Sam",
    "LastName" : "Smith"
}